// web/src/components/FileVersions.vue
<template>
  <el-dialog
    v-model="visible"
    :title="'版本历史 — ' + (file?.name || '')"
    width="600px"
    destroy-on-close
  >
    <div v-if="loading" class="loading-wrapper">
      <el-icon class="is-loading" :size="24"><Loading /></el-icon>
      <span>加载中...</span>
    </div>

    <el-empty v-else-if="versions.length === 0" description="暂无历史版本" :image-size="80" />

    <el-timeline v-else>
      <el-timeline-item
        v-for="ver in versions"
        :key="ver.id"
        :timestamp="formatDate(ver.created_at)"
        placement="top"
      >
        <el-card shadow="hover" class="version-card">
          <div class="version-info">
            <div class="version-main">
              <el-tag size="small" type="info">v{{ ver.version }}</el-tag>
              <span class="version-size">{{ formatFileSize(ver.size) }}</span>
              <span v-if="ver.comment" class="version-comment">{{ ver.comment }}</span>
            </div>
            <div class="version-actions">
              <el-button link type="primary" size="small" @click="handleRestore(ver)">
                回滚到此版本
              </el-button>
              <el-button link type="danger" size="small" @click="handleDelete(ver)">
                删除
              </el-button>
            </div>
          </div>
        </el-card>
      </el-timeline-item>
    </el-timeline>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Loading } from '@element-plus/icons-vue'
import type { FileItem, FileVersion } from '@/types'
import { getFileVersions, restoreVersion, deleteVersion } from '@/api/file'
import { formatFileSize, formatDate } from '@/utils'

const props = defineProps<{
  modelValue: boolean
  file: FileItem | null
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', val: boolean): void
  (e: 'restored'): void
}>()

const visible = ref(props.modelValue)
const loading = ref(false)
const versions = ref<FileVersion[]>([])

watch(() => props.modelValue, (val) => {
  visible.value = val
  if (val && props.file) {
    loadVersions()
  }
})

watch(visible, (val) => {
  emit('update:modelValue', val)
})

async function loadVersions() {
  if (!props.file) return
  loading.value = true
  try {
    const res = await getFileVersions(props.file.id)
    versions.value = res.data?.versions || []
  } catch {
    versions.value = []
  } finally {
    loading.value = false
  }
}

async function handleRestore(ver: FileVersion) {
  if (!props.file) return
  try {
    await ElMessageBox.confirm(
      `确定要回滚到 v${ver.version} 吗？当前版本将自动保存。`,
      '回滚版本',
      { type: 'warning' }
    )
    await restoreVersion(props.file.id, ver.id)
    ElMessage.success('已回滚到该版本')
    loadVersions()
    emit('restored')
  } catch { /* */ }
}

async function handleDelete(ver: FileVersion) {
  if (!props.file) return
  try {
    await ElMessageBox.confirm(`确定要删除 v${ver.version} 吗？`, '删除版本', { type: 'warning' })
    await deleteVersion(props.file.id, ver.id)
    ElMessage.success('版本已删除')
    loadVersions()
  } catch { /* */ }
}
</script>

<style scoped lang="scss">
.loading-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 40px 0;
  color: #909399;
}

.version-card {
  :deep(.el-card__body) {
    padding: 12px 16px;
  }
}

.version-info {
  display: flex;
  justify-content: space-between;
  align-items: center;

  .version-main {
    display: flex;
    align-items: center;
    gap: 10px;

    .version-size {
      font-size: 13px;
      color: #606266;
    }

    .version-comment {
      font-size: 12px;
      color: #909399;
      max-width: 200px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
  }

  .version-actions {
    display: flex;
    gap: 4px;
  }
}
</style>

// web/src/components/FileVersions.tsx
import { useState, useEffect } from 'react'
import { Modal, Spin, Empty, Timeline, Tag, Button, Space, message } from 'antd'
import type { FileItem, FileVersion } from '@/types'
import { getFileVersions, restoreVersion, deleteVersion } from '@/api/file'
import { formatFileSize, formatDate } from '@/utils'

interface Props {
  open: boolean
  file: FileItem | null
  onClose: () => void
  onRestored: () => void
}

export default function FileVersions({ open, file, onClose, onRestored }: Props) {
  const [loading, setLoading] = useState(false)
  const [versions, setVersions] = useState<FileVersion[]>([])

  useEffect(() => {
    if (open && file) {
      loadVersions()
    }
  }, [open, file])

  const loadVersions = async () => {
    if (!file) return
    setLoading(true)
    try {
      const res = await getFileVersions(file.id)
      setVersions(res.data?.versions || [])
    } catch {
      setVersions([])
    } finally {
      setLoading(false)
    }
  }

  const handleRestore = (ver: FileVersion) => {
    if (!file) return
    Modal.confirm({
      title: '回滚版本',
      content: `确定要回滚到 v${ver.version} 吗？当前版本将自动保存。`,
      onOk: async () => {
        await restoreVersion(file.id, ver.id)
        message.success('已回滚到该版本')
        loadVersions()
        onRestored()
      },
    })
  }

  const handleDelete = (ver: FileVersion) => {
    if (!file) return
    Modal.confirm({
      title: '删除版本',
      content: `确定要删除 v${ver.version} 吗？`,
      okType: 'danger',
      onOk: async () => {
        await deleteVersion(file.id, ver.id)
        message.success('版本已删除')
        loadVersions()
      },
    })
  }

  return (
    <Modal
      title={`版本历史 — ${file?.name || ''}`}
      open={open}
      onCancel={onClose}
      width={600}
      footer={null}
      destroyOnClose
    >
      {loading ? (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, padding: '40px 0', color: '#909399' }}>
          <Spin />
          <span>加载中...</span>
        </div>
      ) : versions.length === 0 ? (
        <Empty description="暂无历史版本" imageStyle={{ height: 80 }} />
      ) : (
        <Timeline
          items={versions.map((ver) => ({
            key: ver.id,
            children: (
              <div style={{
                display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                padding: '12px 16px', background: '#fafafa', borderRadius: 8,
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                  <Tag>v{ver.version}</Tag>
                  <span style={{ fontSize: 13, color: '#606266' }}>{formatFileSize(ver.size)}</span>
                  {ver.comment && (
                    <span style={{ fontSize: 12, color: '#909399', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {ver.comment}
                    </span>
                  )}
                  <span style={{ fontSize: 12, color: '#c0c4cc' }}>{formatDate(ver.created_at)}</span>
                </div>
                <Space>
                  <Button type="link" size="small" onClick={() => handleRestore(ver)}>回滚到此版本</Button>
                  <Button type="link" size="small" danger onClick={() => handleDelete(ver)}>删除</Button>
                </Space>
              </div>
            ),
          }))}
        />
      )}
    </Modal>
  )
}
